5 get review by
richnw/nc-games-project pull request #5
Opened 2022-12-13 16:23 UTC by richnw

2022-12-13 16:41 UTC, roisinoreilly approved these changes
Great work!! I just have one pointer on making your test less brittle if you want to implement it, otherwise merge away

2022-12-13 16:41 UTC, roisinoreilly commented on __tests__/app.test.js
> +          title: "Jenga",
to keep this test reusable if we end up patching this review, you might want to use a flexible matcher for everything but the review_id (.toMatchObject, .objectContaining)

2022-12-13 16:41 UTC, roisinoreilly commented on __tests__/app.test.js
> +});
nicely handled

2022-12-13 16:41 UTC, roisinoreilly commented on controllers/errors.controllers.js
> +  } else next(err);
very nicely done

2022-12-15 10:10 UTC, popatre requested changes
Tests are there, just a few things need tweaking

2022-12-15 10:10 UTC, popatre commented on __tests__/app.test.js
> +const { expect } = require("@jest/globals");
Think you dont want this auto import

2022-12-15 10:10 UTC, popatre commented on __tests__/app.test.js
> +        expect(body).toHaveLength(3);
The body needs to be returns in an object, with a key of `comments`

2022-12-15 10:10 UTC, popatre commented on __tests__/app.test.js
> +              review_id: expect.any(Number),
If you've got a review id, and you're requesting id 2, you would ideally check that they all have this id - this would match any comment object at the moment, regardless of whether its for the id you requested

2022-12-15 10:10 UTC, popatre commented on __tests__/app.test.js
> +        console.log(body);
remove console log please

2022-12-15 10:10 UTC, popatre commented on __tests__/app.test.js
> +      .then(({ body }) => {
nice one

2022-12-15 10:10 UTC, popatre commented on controllers/app.controllers.js
> +function getComments(req, res, next) {
Naming wise - might be getting to specify ...byId - just incase you make an endpoint that get all the comments

2022-12-15 10:10 UTC, popatre commented on controllers/app.controllers.js
> +    .then((comments) => res.status(200).send(comments))
Need to send this back in an object

2022-12-15 10:10 UTC, popatre commented on controllers/errors.controllers.js
> +    res.status(err.status).send({ msg: err.msg });
Nice handlers here

2022-12-15 10:10 UTC, popatre commented on models/app.models.js
> +  const dbOutput = await db.query(
If you wanted, you could destructure rows, and use it straight away `const {rows} =... `

2022-12-15 10:23 UTC, richnw commented on __tests__/app.test.js
> +        expect(body).toHaveLength(3);
Sorry. I'm not quite sure what you mean here? The body is currently an array of comment objects which is what the ticket asks for.

2022-12-15 10:34 UTC, richnw commented on controllers/app.controllers.js
> +    .then((comments) => res.status(200).send(comments))
I think this is correct that it is sending an array. It's confusing because this is actually ticket 6 but on branch 5.

2022-12-15 11:02 UTC, richnw commented on controllers/app.controllers.js
> +    .then((comments) => res.status(200).send(comments))
Thanks for the DMs. Sorted now!

2022-12-15 11:03 UTC, richnw commented on __tests__/app.test.js
> +        expect(body).toHaveLength(3);
Thanks for the DMs. Sorted now!

2022-12-15 11:14 UTC, Poonam-raj approved these changes
Nice work, only one tiny comment so you're free to merge this work! 🎉

2022-12-15 11:14 UTC, Poonam-raj commented on app.js
>  app.all("*", handleInvalidPath);
your app.all could be moved to line 20 - general convention is it kind of precedes the error handling section of app.js

2022-12-15 11:18 UTC, merged